
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${db.username}
    password: ${db.password}
    url: ${db.url}

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: ${jpa.ddl-auto}
    properties:
      hibernate:
        show_sql: true
        format_sql: true
      database-platform: org.hibernate.dialect.MySQL8Dialect\
  application:
    name: lotification
  config:
    import: optional:configserver:http://localhost:9999

management:
  endpoints:
    web:
      exposure:
        include: refresh